apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin
  labels:
    app: xxl-job-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job
  template:
    metadata:
      labels:
        name: xxl-job
    spec:
      containers:
        - name: xxl-job
          image: registry.cn-hangzhou.aliyuncs.com/su_wind/xxl-job:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9011
          env:
             - name: JAVA_OPTIONS
               value: -Xms256m -Xmx256m
             - name: -XX:MetaspaceSize
               value: 56m
          readinessProbe:
            successThreshold: 1
          resources:
            limits:
              cpu: '0.5'
              memory: "400Mi"
            requests:
              cpu: '0.1'
              memory: "400Mi"