apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-single
spec:
  selector:
    matchLabels:
      app: mysql-single
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-single
    spec:
      containers:
        - image: mysql:8.0
          name: mysql-single
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123456
          ports:
            - containerPort: 3306
              name: mysql-single
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
