apiVersion: v1
kind: Pod
metadata:
  name: mem-demo
  namespace: mem-example
spec:
  containers:
    - name: memory-demo-ctr
      image: polinux/stress
      resources:
        # 容器将会请求 100 MiB 内存
        requests:
          memory: "100Mi"
          cpu: "1"
        #  容器内存会被限制在 200 MiB 以内
        limits:
          memory: "200Mi"
          cpu: "2"
      command: ["stress"]
      # "--vm-bytes", "150M" 参数告知容器尝试分配 150 MiB 内存。
      args:
        - -cpus
        - "2"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "150M"
        - "--vm-hang"
        - "1"