version: "3.0"
services:
  redis:
    container_name: redis:latest
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /mydata/redis/conf/redis.conf:/etc/redis/redis.conf
      - /mydata/redis/data:/data:rw
      - /mydata/redis/logs:/logs:rw
    command:
      - redis-server /etc/redis/redis.conf --appendonly yes
    networks:
      - redis


networks:
  redis:
    driver: bridge