version: "3.0"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/soft/nginx/conf:/etc/nginx
      - /home/soft/nginx:/home/soft/nginx
      - /etc/hosts:/etc/hosts